### ISSUE TITLE
findall/3 member/2 core dump

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#30]
```
$ cat testmem.pl

isl({L},N) :- L = (_ is _+N).

testmem(Lim) :- findall(Z,(between(1,Lim,N), isl({X}, N),
                           X = (Y is B+_), findall(Y,(between(1,3,B),X),Z)),
	                M),
	        M1 =[[2,3,3],[3,4,4],[4,5,5],[5,6,6],[6,7,7]],
	        !,
	        member(Q,M1), \+member(Q,M),
	        findall([_,_,Q3], member([_,_,Q3],M),F),
                length(F,Lf), write(Lf), nl, false.
```

```
v2.1.8 (main)
$ tpl testmem.pl

?- testmem(1000).
1000
1000
1000
1000
1000
   false.

?- testmem(2000).
2000
2000
malloc(): invalid size (unsorted) 
Aborted (core dumped)

% I see the malloc() error when running testmem(1000) first
% Standalone I get the realloc() error as below

v2.1.8-3-g994c (devel) 
?- testmem(2000).
2000
2000
realloc(): invalid next size
Aborted (core dumped)
```

**Comment by flexoron** [comment]
v2.1.14
```
Now 4000 (elems) but then

?- testmem(4000).
4000
4000
4000
4000
4000
   false.

?- testmem(5000).
5000
5000
malloc(): unsorted double linked list corrupted
Aborted (core dumped)
```

**Comment by flexoron** [comment]
Here I can reproduce "list corrupted" if  testmem(2000) first, then 4000 and finally 5000.
```
?- testmem(2000).
2000
2000
2000
2000
2000
   false.
?- testmem(4000).
4000
4000
4000
4000
4000
   false.
?- testmem(5000).
5000
5000
malloc(): unsorted double linked list corrupted

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at pthread_kill.c:89
#3  0x0000555554e3e256 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x0000555554e257ec in __GI_abort () at abort.c:79
#5  0x0000555554e86878 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x555554fb7599 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#6  0x0000555554e9dc7a in malloc_printerr (str=str@entry=0x555554fba780 "malloc(): unsorted double linked list corrupted")
    at malloc.c:5667
#7  0x0000555554ea10c4 in _int_malloc (av=av@entry=0x555554ff5c60 <main_arena>, bytes=bytes@entry=32) at malloc.c:4006
#8  0x0000555554ea3769 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3674
#9  0x000055555558f398 in alloc_on_heap (q=0x555555ad4e90, nbr_cells=40018) at src/heap.c:104
#10 0x0000555555590a09 in deep_copy_to_heap (q=0x555555ad4e90, p1=0x55555570ae98, p1_ctx=1, copy_attrs=false) at src/heap.c:430
#11 0x00005555555601ec in fn_iso_findall_3 (q=0x555555ad4e90) at src/bags.c:46
#12 0x00005555555fd4f4 in start (q=0x555555ad4e90) at src/query.c:1731
#13 0x00005555555fdc8c in execute (q=0x555555ad4e90, cells=0x55555587be60, nbr_vars=0) at src/query.c:1926
#14 0x00005555555ab29f in run (p=0x5555558746f0, pSrc=0x5555558249e0 "testmem(5000).", dump=true) at src/parser.c:3573
#15 0x00005555555f52e7 in pl_eval (pl=0x55555497f010, s=0x5555558249e0 "testmem(5000).") at src/prolog.c:122
#16 0x000055555555fac4 in main (ac=2, av=0x7fffffffc1d8) at tpl.c:322
```
fyi: I'm away for some while. Good speed! :-)

**Comment by infradig** [comment]
The odd thing is the first 2 numbers come out quickly, then things go off
the rails.

**Comment by infradig** [comment]
Change the second last line to remove the redundant anonymous variables and
it flies.

         findall([_,_,Q3], member([_,_,Q3],M),F),
to
         findall(Q3, member([_,_,Q3],M),F),

There's a problem creating a large number of variable copies in findall.

**Comment by flexoron** [comment]
Not too bad..!!

**Comment by infradig** [comment]
~/trealla (devel) $ time tpl -f testmem.pl -g "testmem(100000);halt"
100000
100000
100000
100000
100000

real 0m2.113s
user 0m2.056s
sys 0m0.052s
