### ISSUE TITLE
Compilation error on Android/Termux app v118

### ISSUE THREAD

**Issue by flexoron** [trealla-prolog/trealla#479]
```
cc -Isrc -I/usr/local/include -DVERSION='"v1.22.61"' -O3 -Wall -Wextra -D_GNU_SOURCE -Wno-deprecated-declarations -funsigned-char  -Wno-unused-function -Wno-unused-parameter -DUSE_ISOCLINE=1 -DUSE_OPENSSL=1   -c -o src/predicates.o src/predicates.c
src/predicates.c:5794:2: warning: implicit declaration of function 'qsort_r' is invalid in C99 [-Wimplicit-function-declaration]
        qsort_r(base, cnt, sizeof(basepair), nodecmp, (void*)q);

ld.lld: error: undefined symbol: qsort_r
>>> referenced by predicates.c
>>>               src/predicates.o:(nodesort)
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by flexoron** [comment]
```
Linux:
gcc version 11.1.0
clang version 12.0.1, 13..0.1
do not need the declaration(see stdlib.h).

I cannot tell much about these systems:

#if __BSD__ || __APPLE__
        qsort_r(base, cnt, sizeof(basepair), (void*)q, nodecmp);
#endif
```

**Comment by flexoron** [comment]
I got something wrong...sorry...
forget what is said above

**Comment by flexoron** [comment]
```
Android/Termux v118
qsort_r() function declaration missing in stdlib.h
```

**Comment by flexoron** [comment]
v1.23.0
```
No warning, no error, test 49 failed

Running tests/tests/test049.pl ...
2c2
< "cdaa"
---
> "adac"
8c8
< [bar(c),bar(d),bar(a),bar(a)]
---
> [bar(a),bar(d),bar(a),bar(c)]

Hint: This test fails under BSD, too.
(dragonflybsd.org, a fine continuation of freebsd4)
```

**Comment by flexoron** [comment]
somehow strange:
```
test 049

?- [user].
foo(a, b, c).
foo(a, b, d).
foo(a, b, a).
foo(a, b, a).
foo(b, c, f).
foo(b, c, e).
   true.
?- bagof(C,foo(_,_,C),L).
   L = "cdaa" % expected

but

?- [user].
foo(a, b, c).
foo(a, b, d).
foo(a, b, a).
foo(a, b, a).
foo(b, c, f).
foo(b, c, e).
foo(c, c, g). % appending this line changes the result
   true.
?- bagof(C,foo(_,_,C),L).
   L = "adac"  % unexpected
```

**Comment by infradig** [comment]
Looks like qsort on Android is not stable.

**Comment by flexoron** [comment]
same in BSD, the man page of qsort is the same, there is a difference with qsort_r (this thunk parameter)
but you've kindly changed that already.

**Comment by flexoron** [comment]
Found.
```
How nice is that?

Linux glibc interals, they use qsort_r/msort

#6  0x00007ffff79044a5 in msort_with_tmp.part () from /usr/lib/libc.so.6
#7  0x00007ffff790488a in qsort_r () from /usr/lib/libc.so.6
#8  0x00005555555b126b in nodesort (q=0x5555557a7aa0, p1=0x55555577c7d0, p1_ctx=75, dedup=false, keysort=true, status=0x7fffffffd5c0) at src/predicates.c:5805
```
```
BSD is clean and does not do such hacks

Tried (bsd) qsort_r without success:
$ man qsort
qsort(), qsort_r(), and heapsort() are not stable // as you said!
The mergesort() algorithm is stable.

predicates.c: mergesort(base, cnt, sizeof(basepair), nodecmp); // parameter compatible

$ tpl
:
?- bagof(C,foo(_,_,C),L).
   L = "cdaa"  % here we are
```
```
Termux

Termux uses Bionic libc and not glibc
(and is BSD compatible haha).
```

**Comment by infradig** [comment]
Are you saying mergesort is available on Android?

**Comment by flexoron** [comment]
No, sorry, see above.

**Comment by flexoron** [comment]
This header file is not too bad:
```
On linux it does the same as before:
#6  0x00007ffff78ed4a5 in msort_with_tmp.part () from /usr/lib/libc.so.6
#7  0x00007ffff78ed88a in qsort_r () from /usr/lib/libc.so.6
#8  0x000055555557e1ff in sort_r (base=0x5555557ad790 ....
#9  0x00005555555b12b3 in nodesort (q=0x5555557ac320 ....
```

```
On Termux and DragonFly it uses sort_r_simple
#4  0x00000000004223c6 in sort_r_cmpswap (a=0x8014939d0 ...
#5  0x0000000000422531 in sort_r_simple (base=0x8014939d0 ...
#6  0x000000000042290e in sort_r (base=0x8014939d0 ...
#7  0x000000000045454c in nodesort (q=0x80162a900 ...

test049 succeeds!
```

```
Usage:
predicate.c
#include "sort_r.h"
:
static int nodecmp(const void *ptr1, const void *ptr2, void *vp)  // vp = NULL
sort_r(base, cnt, sizeof(basepair), nodecmp, NULL);
nodecmp(&base[i], &base[i-1],NULL)

sort_r.h
Do not define anything for these systems, fall back to  sort_r_simple()

#if (defined __APPLE__ || defined __MACH__ || defined __DARWIN__ || \
     defined __FreeBSD__ || defined __DragonFly__ || defined __TERMUX__)
/* #  define _SORT_R_BSD */ 


__TERMUX__ must be defined somewhere, perhaps in the Makefile
```

**Comment by flexoron** [comment]
v1.23.18
```
On BSD mergesort() produces the expected result of test049.

Termux seems to be a mix of Linux and BSD and Android.
Neither mergesort() nor qsort_r() is found but just qsort() which is unstable.
The platform tag __ANDROID__ should not be used because inside, Trealla is not a real Android app.

Termux users can patch their Trealla environment according to the usage description(see above).

Hints:
Internally, qsort() Linux applies a kind of fall back qsort_r() (perhaps correlated with sorting utf8)
There might be UTF8 issues on BSD but these depend on your environment.

@infradig: the dragonfly thanked for providing tag __DragonFly__ 
```
